#!name=JD

#!desc=JD脚本

[Script]
#京东比价 = type=http-response,requires-body=true,pattern=^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig),max-size=1048576,script-path=https://raw.githubusercontent.com/yichahucha/surge/master/jd_price.js,enable=false
#获取京东Cookie = type=http-request,pattern=https:\/\/api\.m\.jd\.com\/client\.action.*functionId=signBean,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js, enable=false
#获取京东Cookie = type=http-request,pattern=^https:\/\/(api\.m|me-api|ms\.jr)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?|gw\/generic\/hy\/h5\/m\/appSign\?),script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js, enable=false
#获取京东Cookie = type=http-request,pattern=^https:\/\/(api\.m|me-api|ms\.jr)\.jd\.com\/(client\.action\?functionId=signBean|user_new\/info\/GetJDUserInfoUnion\?|gw\/generic\/hy\/h5\/m\/appSign\?),script-path=https://raw.githubusercontent.com/ChuheGit/1/main/Script/jd_scripts/JD_extra_cookie.js, enable=false
#京东白条 = type=cron,cronexpr="0 0,9 * * *",timeout=10,script-path=https://raw.githubusercontent.com/yangtingxiao/QuantumultX/master/scripts/jd/jd_baiTiao.js, enable=false
#京东特权值 = type=cron,cronexpr=5 8 * * *,timeout=20,script-path=https://raw.githubusercontent.com/iisams/Scripts/master/liwo/jdtqz.js, enable=false
#获取所有互助码 = type=cron,cronexpr="20 13 * * 6",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_get_share_code.js, enable=false
#注销京东会员卡 = type=cron,cronexpr="10 23 * * 6",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_unbind.js, enable=false
取关京东店铺和商品 = type=cron,cronexpr="55 23 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_unsubscribe.js, enable=false
京东多合一签到NobyDa = type=cron,cronexpr="1 0 * * *",timeout=20,script-path=https://raw.githubusercontent.com/NobyDa/Script/master/JD-DailyBonus/JD_DailyBonus.js, enable=true
#京东签到 = type=cron,cronexpr="0 0 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_bean_sign.js, enable=false
#京东直播 = type=cron,cronexpr="10-20/5 12 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live.js, enable=true
#京东排行榜 = type=cron,cronexpr="11 9 * * *",timeout=200,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_rankingList.js, enable=true
#京东抽奖机 = type=cron,cronexpr="11 1 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_lotteryMachine.js, enable=true
东东农场 = type=cron,cronexpr="5 6-18/6 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_fruit.js, enable=true
种豆得豆 = type=cron,cronexpr="1 7-21/2 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_plantBean.js, enable=true
#领京豆额外奖励抢京豆 = type=cron,cronexpr="12 8 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_bean_home.js, enable=true
#赚京豆 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_syj.js, cronexpr="10 8 * * *", timeout=3600, enable=true
#闪购盲盒 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_sgmh.js, cronexpr="20 8 * * *", timeout=3600, enable=true
#进店领豆 = type=cron,cronexpr="8 0 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_shop.js, enable=true
#摇京豆 = type=cron,cronexpr="5 0,23 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_club_lottery.js, enable=true
#签到领现金 = type=cron,cronexpr="2 0-23/4 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_cash.js, enable=true
#领金贴 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_jin_tie.js, cronexpr="10 0 * * *", timeout=3600, enable=true
#早起福利 = type=cron,script-path=https://raw.githubusercontent.com/he1pu/JDHelp/main/jd_goodMorning.js, cronexpr="30 6 * * *", timeout=3600, enable=true
#升级赚京豆 = type=cron,script-path=https://raw.githubusercontent.com/he1pu/JDHelp/main/jd_upgrade.js, cronexpr="21 9 * * *", timeout=3600, enable=true
#每日抽奖 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_daily_lottery.js, cronexpr="13 1,22,23 * * *", timeout=3600, enable=true
东东健康社区 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_health.js, cronexpr="13 1,6,22 * * *", timeout=3600, enable=true
东东健康社区收集能量 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_health_collect.js, cronexpr="5-45/20 * * * *", timeout=3600, enable=true
#金榜创造营 = type=cron,script-path=https://raw.githubusercontent.com/qqsdff/script/main/jd/jd_jbczy.js, cronexpr="0 8 21-31 5-12 *", timeout=3600, enable=true
#5G超级盲盒 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_mohe.js, cronexpr="0 0,1-23/3 * * *", timeout=3600, enable=true
#5G狂欢城 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_carnivalcity.js, cronexpr="0 0,6,12,18 * * *", timeout=3600, enable=false
#京东超级盒子 = type=cron,script-path=https://raw.githubusercontent.com/monk-coder/dust/dust/normal/adolf_superbox.js, cronexpr="15 9,20 * 5,6 *", timeout=3600, enable=true
#京东小魔方 = type=cron,script-path=https://raw.githubusercontent.com/monk-coder/dust/dust/i-chenzhe/z_xmf.js, cronexpr="10 10 4-6 4 *", timeout=3600, enable=true
#京小兑 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_jxd.js, cronexpr="30 11 * * *", timeout=3600, enable=false
#京东国际盲盒 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_global_mh.js, cronexpr="0 9,12,20,21 * * *", timeout=3600, enable=false
#女装盲盒 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_nzmh.js, cronexpr="35 1,23 * * *", timeout=3600, enable=false
##小鸽有礼2 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_xgyl.js, cronexpr="30 7 * * *", timeout=3600, enable=true
#京东快递签到 = type=cron,cronexpr="10 0 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_kd.js, enable=true
#东东萌宠 = type=cron,cronexpr="15 6-18/6 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_pet.js, enable=true
#京东赚赚 = type=cron,cronexpr="30 0 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_jdzz.js, enable=true
#京东秒秒币 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_ms.js, cronexpr="22 7 * * *", timeout=200, enable=true
#京东点点券 = type=cron,cronexpr="10 0,20 * * *",timeout=3600,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_necklace.js, enable=true
#整点京豆雨= type=cron,script-path=https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd_super_redrain.js, cronexpr="1 0-23/1 * * *",timeout=200, enable=true
#金口碑奖投票 = type=cron,script-path=https://raw.githubusercontent.com/i-chenzhe/qx/main/z_mgold.js, cronexpr="5 10 * 3 *", timeout=3600, enable=false
#5G超级盲盒 = type=cron,script-path=https://raw.githubusercontent.com/i-chenzhe/qx/main/z_super5g.js, cronexpr="5 1,6,11,16,21 * 3-4 * ", timeout=3600, enable=false
#众筹许愿池 = type=cron,script-path=https://raw.githubusercontent.com/i-chenzhe/qx/main/z_wish.js, cronexpr="10 10,15 13-20 3 *", timeout=3600, enable=false
#半点京豆雨= type=cron,script-path=https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd_half_redrain.js, cronexpr="30 20-23/1 * * *",timeout=200, enable=true
#整点京豆雨= type=cron,script-path=https://raw.githubusercontent.com/nianyuguai/longzhuzhu/main/qx/jd_super_redrain.js, cronexpr="1 0-23/1 * * *",timeout=200, enable=true
#直播间红包雨 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live_redrain2.js, cronexpr="0,1 19-21/1 * * *", timeout=200, enable=false
#官方号直播红包雨 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live_redrain_offical.js, cronexpr="0 0,9,11,13,15,17,19,20,21,23 * * *", timeout=200, enable=false
#半点红包雨 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live_redrain_half.js, cronexpr="30,31 12-23/1 * * *", timeout=200, enable=false
#年货直播红包雨 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live_redrain_nian.js, cronexpr="0 0,9,11,13,15,17,19,20,21,23 3,5,20-30/1 1,2 *", timeout=200, enable=false
#超级直播间红包雨 = type=cron,script-path=https://raw.githubusercontent.com/HAIIIYA/Shadowrocket/main/jd_live_redrain.js, cronexpr="30,31 20-23/1 9,12 3 *", timeout=3600, enable=true

[MITM]
hostname = api.m.jd.com,ms.jr.jd.com,me-api.jd.com
